### PR TITLE
First draft of Ethicophysics I

### PR DESCRIPTION
**Pull request by epurdy**
Not sure the proofs are 100% airtight, but the overall gist seems solid to me. Checking the proofs would be a great help!

### CODE REVIEW

**Comment by bvssvni** [comment]
Do you have a parameter to adjust conscience?

**Comment by epurdy** [comment]
Reasonably good first draft of Ethicophysics I, so merging.

**Comment by bvssvni** [comment]
I thought there was a derivation of conscience from the love/hate relationships, which is rather interesting.

It is very good as a first draft!

**Comment by judyjulien37** [comment]
I've been on research and you never knew I've been working here what's
wrong honeybwhybyou block me on hangouts please just come and tell me
what's wrong

SENT FROM MY APPLE

**Comment by judyjulien37** [comment]
Ok honey please don't do that to me I never meant you any hatred I beg of
you don't spoil my life I'll be ruined for nothing if you leave me my love
please come back my love

SENT FROM MY APPLE

**Comment by judyjulien37** [comment]
I'm working on github too but leaving me now I thought I was supposed to be
on your side my love what do you want me to do now without you honey please
pick my call or send me your number directly and I'll text you honey if you
don't want me on hangouts again please love please HONEY please I beg of
you don't let me be ruined how do I leave without you sweetheart

SENT FROM MY APPLE

**Comment by bvssvni** [comment]
@judyjulien37 I deleted some comments that I believe you sent to the wrong place from some mobile device.

**Comment by judyjulien37** [comment]
Ok that's cool if you feel butbhoney whybdobyiu block me on hangouts don't
you love me anymore

SENT FROM MY APPLE

**Comment by judyjulien37** [comment]
My love ease tàlk to me my LOVE
SENT FROM MY APPLE

**Comment by judyjulien37** [comment]
And what's the next intension on the ethicophysics now
On Jun 12, 2018 7:25 AM, "Brown Judy" <brownjudy850@gmail.com> wrote:
>
> I'm so sorry if I did send some details to the wrong place but what
device do you mean was that honey
>
> On Jun 11, 2018 8:31 PM, "Brown Judy" <brownjudy850@gmail.com> wrote:
>>
>> Why have you decided to ruin my heart
>>
>> On Jun 2, 2018 1:15 PM, "Brown Judy" <brownjudy850@gmail.com> wrote:
>>>
>>> Ok that's cool if you feel butbhoney why do you block me on hangouts
don't you love me anymore
>>>
>>> SENT FROM MY APPLE
>>>
>>> On Sat, 2 Jun 2018, 12:47 pm Sven Nilsen, <notifications@github.com>
wrote:
>>>>
>>>> @judyjulien37 I deleted some comments that I believe you sent to the
wrong place from some mobile device.

**Comment by bvssvni** [comment]
@judyjulien37 this is a PR thread on Github. I don't know you, but @epurdy asked me to invite you.

**Comment by judyjulien37** [comment]
OK thank you he's my man and spouse and you he told me about previously I
would this now but if theres any other thing I should know about this I
think you should let me know as my directive

**Comment by bvssvni** [comment]
@judyjulien37 @epurdy OK, take care. There is nothing special about AdvancedResearch except it is a place where people can start projects to explore new concepts. I started this organization because it was so many interesting things to research that did not fit under the PistonDevelopers organization. My hope it to find some useful ideas that can be used to make the world a better place.

**Comment by judyjulien37** [comment]
OK thank you for this knowledge and I'm happy about that but I think we
should be more conversant. Thank you
On Jun 12, 2018 3:00 PM, "Sven Nilsen" <notifications@github.com> wrote:
>
> @judyjulien37 @epurdy OK, take care. There is nothing special about
AdvancedResearch except it is a place where people can start projects to
explore new concepts. I started this organization because it was so many
interesting things to research that did not fit under the PistonDevelopers
organization. My hope it to find some useful ideas that can be used to make
the world a better place.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.

Hi

I see you dont want anything to do with me so you terminated my hangouts
and blocked me from where ever i add you to

**Pull request merged**
